### PR TITLE
Rules

### PR DESCRIPTION
**Pull request by signalwerk**
What is the rule/criteria to combine under one company multiple orgas? At Liip there is the product «rokka.io»

### CODE REVIEW

**Comment by CodeOneTwo** [comment]
@maemst Any ideas

**Comment by olibrian** [comment]
Same here at Puzzle ITC, we have oss products in own organizations.

**Comment by maemst** [comment]
Good point! The question is: How much do Liip employees contribute to repos inside rokka.io? What metric could we use to answer this question?

**Comment by signalwerk** [comment]
@maemst well since it is a product owned by Liip I would say it might be arround 99% – wild guessing... So in the rokka-org the code is probably to a high percentage originally written by Liip employees. Whereas the orga `liip-forks` is only forks with a minor code-contributions by Liip (nature of forks).

**Comment by maemst** [comment]
Sorry for the +1 year delay... I added now https://github.com/rokka-io to the Liip AG institution: https://github.com/digital-sustainability/oss-github-benchmark/commit/9352901a0def5034c6f7dbf16b9881b17ba06615

**Pull request closed without merging**
